apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: demo
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ["sh", "-c", "echo Hello AAP! && sleep 3600"]
