apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: demo
spec:
  containers:
    - name: myapp-container
      image: quay.io/bhouse/busybox:latest
      command: ["sh", "-c", "echo Hello World! && sleep 3600"]
      resources:
        requests:
          memory: 128mb